### ISSUE TITLE
db errors on latest version.

### ISSUE THREAD

**Issue by Riveir** [azerothcore/mod-ah-bot#53]
![2022-02-05 (7)](https://user-images.githubusercontent.com/96812524/152672063-eb5fd8cb-6d3c-4696-9fe5-d619b88d5786.png)
So I am using the most recent version of the core (AzerothCore rev. cfb171efda7e 2022-02-05 16:32:25 -0500 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) as of the posting of this issue as well as the most current version of the ah-bot mod. I compiled the core with no modules and get no error, but with the ah-bot module I get this error in the world server. 
commit hash cfb171efda7e1376c3f771f3fca517a4a30bbe67
  > Incorrect value '-34040' for type 'unsigned int'. Value is raw ? 'false'
   > Table name 'npc_vendor'. Field name 'item'

**Comment by LannyE** [comment]
I am getting the exact same error.

**Comment by Riveir** [comment]
recompiled again today using this commit 759b945a1357bbc02c47dd366d3aa02b99f9457e .... Getting the same result.

**Comment by bing88868** [comment]
Me too, hope it gets fixed!

**Comment by scarecr0w12** [comment]
Issue is in the Base world SQL, not an issue with AHbot, its due to an invalid Item ID

**Comment by Riveir** [comment]
> Issue is in the Base world SQL, not an issue with AHbot, its due to an invalid Item ID

Ok. I have no idea how to properly resolve this myself. I am going to close the issue and hopefully figure out in the next few days how to submit this as a core issue.   :(

**Comment by Riveir** [comment]
I was told to close this here and open it on the core then told to open it here so. Here's what happened after I closed it. 
[> Open an issue on the mod repo @Riveir](https://github.com/azerothcore/azerothcore-wotlk/issues/10625#issuecomment-1037821410)

**Comment by scarecr0w12** [comment]
> 

ok can you explain why then it is the only negative ID within that table?

**Comment by Kitzunu** [comment]
Negativt ID is a reference to the npc_vendor.id field
And the issue here is that the field is uint32 (accepta negative values) but in this module, instead of passing it as uint, it is trying to pass it as int32 which doesnt allow negative Numbers.

You're free to check my PR to understand the context

**Comment by scarecr0w12** [comment]
Your response doesn't answer my question, since the Value that is being referenced in the 'error' is an actual item and is in the table incorrectly since no item ID value should be negative. So please provide more detailed information specifically regarding why this item value is represented by a negative when it should not in fact be so, Regardless of if the module is or is not passing a signed or unsigned value.

**Comment by Riveir** [comment]
Some reason I didn't get notified my issued was closed. Is that normal?
