### ISSUE TITLE
Bug: AHBot uses only two Chars

### ISSUE THREAD

**Issue by Raz0r1337** [azerothcore/mod-ah-bot#99]
### Current Behaviour

Hello,
i use the new feature that the Bot uses more then one char from the AHBot Account.
But it uses only two of the ten characters of the Account. It loads all ten chars but uses only the first two of them.

AHBot [1]: initialization complete
AHBot [2]: initialization complete
AHBot [3]: initialization complete
AHBot [4]: initialization complete
AHBot [5]: initialization complete
AHBot [6]: initialization complete
AHBot [7]: initialization complete
AHBot [8]: initialization complete
AHBot [9]: initialization complete
AHBot [10]: initialization complete

Here the SQL export of my Auctionhouse database. Under itemowner we can see that it only uses the first two chars.

### Expected Behaviour

The AHBot should use all ten chars for auctions.

### Steps to reproduce the problem

Simply create ten chars in the account and set the GUID value in the conf to 0.

### Extra Notes

I have deleted all the old auctions once in the DB and I buy the auction house empty and start the AH bot in the hope that it is a fail because of the old config or so but it didn't help.

I have deleted and recreated the ahbot account and this do nothing.

Still the first two chars.

### AC rev. hash/commit

AzerothCore rev. 27b243e7b2aa 2024-08-18 23:02:22 +0800 (Playerbot branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 68.
Connection peak: 1.
Laufzeit des Servers: 14 minute(s) 46 second(s)
Update time diff: 3ms. Last 500 diffs summary:
|- Mean: 4ms
|- Median: 1ms
|- Percentiles (95, 99, max): 11ms, 12ms, 13ms
Using SSL version: OpenSSL 3.0.13 30 Jan 2024 (library: OpenSSL 3.0.13 30 Jan 2024)
Using Boost version: 1.83.0
Using CMake version: 3.28.3
Using MySQL version: 101108
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.8.12-1-pve
Worldserver listening connections on port %u
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /home/acore/server/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/acore/server/data/vmaps. Total size: 1330813631 bytes
mmaps directory located in /home/acore/server/data/mmaps. Total size: 2258857236 bytes
Default DBC locale: deDE.
All available DBC locales: enUS deDE
Using World DB: ACDB 335.12-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- BreakingNewsOverride
|- mod-ah-bot
|- mod-anticheat
|- mod-autobalance
|- mod-groupquests
|- mod-playerbots
|- mod-solo-lfg
|- mod-weekendbonus

### Operating system

Ubuntu 22.04

### Custom changes or Modules

mod-playerbot
mod-anticheat
mod-ah-bot
mod-autobalance
mod-groupquests
mod-solo-lfg
mod-weekendbonus
BreakingNewsOverride

**Comment by kewinrausch** [comment]
Greetings,
Can you share your module configuration file (mod_ahbot.conf.dist)?
Also can you try to run the module with AuctionHouseBot.TRACE_SELLER = 1? Try to enable tracing and share the log of the server (Server.log) so we can get an idea of why such bots are run and, if they are, why the decided to not sell anything.

I suspect that the first two sold all the items within the configured limits and the remaining got nothing left.
There is no load balancing strategy yet for the bots.

**Comment by kewinrausch** [comment]
Ok, so this seems to be what I was thinking about.
Take for example the neutral auction house (number 7); you've got the first bot selling 200 on 200 requested items and the second selling 50 on 50 requested items. After that nothing since the default max has been hit.
```
AHBot [1]: auctionhouse 7, req=200, sold=200, aboveMin=false, aboveMax=false, loopBrk=0, noNeed=364, tooMany=0, binEmpty=0, err=0
AHBot [2]: auctionhouse 7, req=50, sold=50, aboveMin=false, aboveMax=false, loopBrk=0, noNeed=174, tooMany=0, binEmpty=0, err=0
```
If you haven't modified the default setup, in fact the max items is 250 (see mod_auctionhousebot, maxitems column):
```
(7,'Neutral',250,250,0,27,12,10,1,0,0,0,10,30,8,2,0,0,100,150,150,250,800,1400,1250,1750,2250,4550,3250,5550,5250,6550,70,100,70,100,80,100,75,100,80,100,80,100,80,100,0,0,3,2,1,1,1,1,3,5,12,15,20,22,1,1);
```

You will be probably able to see the error if you enable debugging the Seller (but the log will be very verbose).
Here the condition probably triggered (AuctionHouseBot.cpp:568)
```
    if (auctions >= maxItems)
    {
        aboveMax = true;

        if (config->DebugOutSeller)
        {
            LOG_ERROR("module", "AHBot [{}]: Auctions at or above maximum", _id);
        }

        return;
    }
```

This seems to be a configuration problem, not a bug technically.

So here the solutions (depending on what you desire):
- Increase the maxitems in order to have _**at least**_ 200 items per bot (200 * number of bots = 200 * 10 = 2000). 200 is the default loop break, so the bot stops at 200 at every try. Take into account that with the increase of people on the auction house the amount of items in the bots hands will decrease: the bots is organized to fill up empty space from players. If players will sell 2000 items, the bots will not be visible on the market.
- Setup `AuctionHouseBot.ConsiderOnlyBotAuctions = 1` to allow each bot to **_always keep_** 250 items on the market.

**Comment by Raz0r1337** [comment]
Super thank you.

I never said there is a bug. This was the category the that fits most on my case. 😉

I'm using the standard config file without changes. I only enabled the seller and buyer.

I've tried to increase the items above 200 in the past but without ConsiderOnlyBotAuctions the bot only uses the first char.

I have set this config values now:

ItemsPerCycle to 2000
ConsiderOnlyBotAuctions to 1

And this works.

The ahbot now starts now over 19000 auctions and every bot is visible. Many many auctions. 🤣 I use this workaround and wait for the load balancer update for the ahbot.

I thank you a lot for helping me. You are awesome.

**Comment by Raz0r1337** [comment]
Ok,
now i have another problem.
The bot now creates after 10 hours of online idle time over 4 million auctions.
The server is online but it doesnt respond on login tries. After a cleanup from the autions of the db and configreset everything is normal and the server respond.

Ist the option ItemsPerCycle the wrong choice from me to increase the items that can be used from the bot?

**Comment by kewinrausch** [comment]
Try to set this up like the following:
- Restore `ItemsPerCycle` to 200 (this is in the configuration file)
- Keep `ConsiderOnlyBotAuctions` to 1 (this is in the configuration file)
- Keep `MaxItems` to 250 (this is in the database) as for default

This will allow to keep 250 items per bot, so for 10 bots you will have an auction house with around 2500 items.
If you want to keep number lower you can play with the `MaxItems` and consider that will be count as maximum **_for each bot_**.

With the `ConsiderOnlyBotAuctions` you have to multiply every limit for the number of bots, since every bot just consider itself.

**Comment by kewinrausch** [comment]
You can also keep all the values with their standard value and just decrease the `ItemsPerCycle` configuration to give an opportunity to all the bots. Try setting this up to 20 for example.

**Comment by Raz0r1337** [comment]
Oh, it seems that I have misunderstanding the config and your post. 😅 Lost in Translation.

With ItemsPerCycle set to 20 and everything else at default it work now how expected.

With the last solution:
ItemsPerCycle to 200
ConsiderOnlyBotAuctions to 1
MaxItems to 250

I have a weird issue.
All ten bots work but they put auction over auction in the ah. By 14250 i stopped the server and set it back to default.

I think I broke my word DB or something.
I deleted all tables of the world DB and imported a fresh one. But I haven't tested this solution again.

I think I stay at your solution with ItemsPerCycle and test the other next day's when I have time. If you want can I share my logs of these test if you want to check if the bot work correctly.

Thank you very much for helping me.

**Comment by Raz0r1337** [comment]
So I already tried again.

I set max items to 2500 for alliance, horde and neutral and everything else to standard. Now the bot makes 400 auctions and uses only the first two chars. If I set consideronlybotauctions to 1 the bot creates many many auctions and uses only the first two chars. After 2600 auctions I stopped this and deleted all auctions.

Now I use following settings.
maxitemspercycle to 20.
Consideronlybotauctions to 0

Now it creates 217 auctions and every Bot is in the list.

If I set Consideronlybotauctions to 1 then the bot creates many auctions. After 7600 i stopped again and set it to 0

I think I stay at this options for now.

But why the bot creates so many auctions?
I thought it was 250 items * 10 bots = 2500 auctions.
